# Generated by Django 5.1.2 on 2026-03-03 15:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=255)),
                ('needs_hardware', models.BooleanField(default=False)),
                ('needs_software', models.BooleanField(default=False)),
                ('needs_services', models.BooleanField(default=False)),
                ('asset_count_range', models.CharField(max_length=50)),
                ('location_count', models.CharField(blank=True, max_length=20)),
                ('additional_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('quoted', 'Quoted'), ('closed', 'Closed')], default='new', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfq_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rfq_submission',
                'ordering': ['-created_at'],
            },
        ),
    ]
