# Generated by Django 5.1.2

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("asset_register", "Asset Register Creation"),
                            ("verification", "Asset Verification"),
                            ("disposal", "Asset Disposal Support"),
                            ("training_outsource", "Asset Management Training"),
                            ("full_outsource", "Asset Management Outsourcing"),
                        ],
                        max_length=30,
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("company_name", models.CharField(max_length=255)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(max_length=100)),
                ("asset_count_estimate", models.CharField(blank=True, max_length=50)),
                ("site_count", models.IntegerField(default=1)),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("urgent", "Urgent (< 2 weeks)"),
                            ("standard", "Standard (1 month)"),
                            ("flexible", "Flexible"),
                        ],
                        default="standard",
                        max_length=20,
                    ),
                ),
                ("intake_data", models.JSONField(default=dict)),
                ("additional_requirements", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("reviewing", "Under Review"),
                            ("scoped", "Proposal Sent"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "service_request",
                "ordering": ["-created_at"],
            },
        ),
    ]
