# Generated by Django 5.1.2 on 2026-04-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_scannerfeature_tagcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationitem',
            name='location',
            field=models.CharField(choices=[('header_main', 'Header — Main'), ('footer_platform', 'Footer — Platform'), ('footer_resources', 'Footer — Resources')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pageblock',
            name='block_type',
            field=models.CharField(choices=[('hero', 'Hero'), ('feature_grid', 'Feature Grid'), ('guided_path', 'Guided Path'), ('workflow', 'Workflow'), ('pricing', 'Pricing'), ('text', 'Text'), ('cta_banner', 'CTA Banner'), ('stats_row', 'Stats Row'), ('logo_carousel', 'Logo Carousel'), ('image_text', 'Image + Text'), ('video', 'Video'), ('testimonials_section', 'Testimonials Section')], max_length=30),
        ),
    ]
