# Generated by Django 5.1.2 on 2026-04-28 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_pageblock_testimonials_section_choice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessions_heading', models.CharField(default='Upcoming Sessions', max_length=255)),
                ('no_sessions_message', models.TextField(default='No upcoming sessions at this time. Check back soon.')),
                ('low_seats_template', models.CharField(default='Only {count} seat{plural} remaining', help_text='Use {count} for seat number and {plural} for s/empty.', max_length=255)),
                ('register_button_label', models.CharField(default='Register Now', max_length=100)),
                ('full_button_label', models.CharField(default='Session Full', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'training page settings',
                'verbose_name_plural': 'training page settings',
                'db_table': 'cms_training_page_settings',
            },
        ),
    ]
