# Generated by Django 5.1.2 on 2026-04-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_seed_training_page_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='cta_primary_link',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='cta_primary_text',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
