# Generated by Django 5.1.2 on 2026-04-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_alter_herosection_cta_primary_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageblock',
            name='key',
            field=models.CharField(blank=True, db_index=True, help_text="Stable lookup key (e.g. 'arcplus_lifecycle'). Used by frontend to resolve a specific block.", max_length=50),
        ),
        migrations.AlterField(
            model_name='pageblock',
            name='block_type',
            field=models.CharField(choices=[('hero', 'Hero'), ('feature_grid', 'Feature Grid'), ('guided_path', 'Guided Path'), ('workflow', 'Workflow'), ('pricing', 'Pricing'), ('text', 'Text'), ('cta_banner', 'CTA Banner'), ('stats_row', 'Stats Row'), ('logo_carousel', 'Logo Carousel'), ('image_text', 'Image + Text'), ('video', 'Video'), ('testimonials_section', 'Testimonials Section'), ('intro', 'Section Intro'), ('feature_comparison', 'Feature Comparison')], max_length=30),
        ),
    ]
