# Generated by Django 5.1.2 on 2026-05-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_add_password_reset_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='trigger_type',
            field=models.CharField(choices=[('trial_welcome', 'Trial Welcome'), ('trial_reminder_7d', 'Trial Reminder (7 days)'), ('trial_reminder_3d', 'Trial Reminder (3 days)'), ('trial_expired', 'Trial Expired'), ('quote_received', 'Quote Received'), ('quote_received_admin', 'Quote Received (Admin)'), ('quote_response', 'Quote Response'), ('training_confirmation', 'Training Confirmation'), ('service_request', 'Service Request'), ('payment_receipt', 'Payment Receipt'), ('password_reset', 'Password Reset'), ('email_verification', 'Email Verification')], max_length=30, unique=True),
        ),
    ]
