# Generated by Django 5.1.2 on 2026-03-03 15:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArcplusTrialSignup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('plan', models.CharField(choices=[('starter', 'Starter'), ('growth', 'Growth'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='growth', max_length=30)),
                ('asset_count_estimate', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending Provisioning'), ('provisioned', 'Provisioned'), ('active', 'Active Trial'), ('converted', 'Converted'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('provisioned_at', models.DateTimeField(blank=True, null=True)),
                ('provisioned_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trial_signups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscriptions_trialsignup',
                'ordering': ['-created_at'],
            },
        ),
    ]
