# Generated by Django 5.1.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="arcplustrialsignup",
            name="trial_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="arcplustrialsignup",
            name="trial_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="arcplustrialsignup",
            name="reminder_sent_day7",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="arcplustrialsignup",
            name="reminder_sent_day3",
            field=models.BooleanField(default=False),
        ),
    ]
