# Generated by Django 5.1.2

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "industry",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("logistics", "Logistics & Warehousing"),
                            ("manufacturing", "Manufacturing"),
                            ("healthcare", "Healthcare"),
                            ("defense", "Defense & Government"),
                            ("real_estate", "Real Estate & Facilities"),
                            ("it", "IT Asset Management"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("country", models.CharField(blank=True, max_length=100)),
                (
                    "size_range",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1-50", "1\u201350 employees"),
                            ("51-200", "51\u2013200 employees"),
                            ("201-1000", "201\u20131,000 employees"),
                            ("1001+", "1,000+ employees"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "organization",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="accounts.organization",
            ),
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("rfq_status_change", "RFQ Status Changed"),
                            ("trial_provisioned", "Trial Provisioned"),
                            ("trial_status_change", "Trial Status Changed"),
                            ("user_deactivated", "User Deactivated"),
                            ("user_role_change", "User Role Changed"),
                            ("product_created", "Product Created"),
                            ("product_updated", "Product Updated"),
                            ("product_deleted", "Product Deleted"),
                            ("service_status_change", "Service Request Status Changed"),
                            (
                                "training_status_change",
                                "Training Registration Status Changed",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                ("resource_type", models.CharField(max_length=50)),
                ("resource_id", models.CharField(max_length=100)),
                ("changes", models.JSONField(default=dict)),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_log",
                "ordering": ["-created_at"],
            },
        ),
    ]
