# Generated by Django 5.1.2 on 2026-04-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_organization_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('rfq_status_change', 'RFQ Status Changed'), ('trial_provisioned', 'Trial Provisioned'), ('trial_status_change', 'Trial Status Changed'), ('user_deactivated', 'User Deactivated'), ('user_role_change', 'User Role Changed'), ('product_created', 'Product Created'), ('product_updated', 'Product Updated'), ('product_deleted', 'Product Deleted'), ('service_status_change', 'Service Request Status Changed'), ('training_status_change', 'Training Registration Status Changed'), ('cms_settings_update', 'CMS Settings Updated'), ('cms_meta_create', 'CMS Page Meta Created'), ('cms_meta_update', 'CMS Page Meta Updated'), ('cms_meta_delete', 'CMS Page Meta Deleted'), ('cms_hero_create', 'CMS Hero Created'), ('cms_hero_update', 'CMS Hero Updated'), ('cms_hero_delete', 'CMS Hero Deleted'), ('cms_block_create', 'CMS Block Created'), ('cms_block_update', 'CMS Block Updated'), ('cms_block_delete', 'CMS Block Deleted'), ('cms_nav_create', 'CMS Nav Item Created'), ('cms_nav_update', 'CMS Nav Item Updated'), ('cms_nav_delete', 'CMS Nav Item Deleted'), ('cms_media_upload', 'CMS Media Uploaded'), ('cms_media_update', 'CMS Media Updated'), ('cms_media_delete', 'CMS Media Deleted'), ('cms_gallery_add', 'CMS Gallery Image Added'), ('cms_service_create', 'CMS Service Created'), ('cms_service_update', 'CMS Service Updated'), ('cms_service_delete', 'CMS Service Deleted'), ('cms_module_create', 'CMS Module Created'), ('cms_module_update', 'CMS Module Updated'), ('cms_module_delete', 'CMS Module Deleted'), ('cms_pricing_create', 'CMS Pricing Created'), ('cms_pricing_update', 'CMS Pricing Updated'), ('cms_pricing_delete', 'CMS Pricing Deleted'), ('cms_support_tier_create', 'CMS Support Tier Created'), ('cms_support_tier_update', 'CMS Support Tier Updated'), ('cms_support_tier_delete', 'CMS Support Tier Deleted'), ('cms_case_study_create', 'CMS Case Study Created'), ('cms_case_study_update', 'CMS Case Study Updated'), ('cms_case_study_delete', 'CMS Case Study Deleted'), ('cms_submit', 'CMS Content Submitted'), ('cms_approve', 'CMS Content Approved'), ('cms_publish', 'CMS Content Published'), ('cms_archive', 'CMS Content Archived'), ('cms_unpublish', 'CMS Content Unpublished'), ('cms_rollback', 'CMS Content Rolled Back'), ('cms_scheduled_publish', 'CMS Scheduled Publish')], max_length=50),
        ),
    ]
