# Generated by Django 5.1.2

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "product_category",
                "ordering": ["order", "name"],
                "verbose_name_plural": "product categories",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("short_description", models.CharField(max_length=400)),
                ("full_description", models.TextField(blank=True)),
                ("image_hero", models.CharField(blank=True, max_length=500)),
                ("image_context", models.CharField(blank=True, max_length=500)),
                ("image_detail", models.CharField(blank=True, max_length=500)),
                ("image_usecase", models.CharField(blank=True, max_length=500)),
                ("specifications", models.JSONField(default=dict)),
                ("is_configurable", models.BooleanField(default=False)),
                ("is_recommended", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("datasheet_url", models.CharField(blank=True, max_length=500)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="products.productcategory",
                    ),
                ),
            ],
            options={
                "db_table": "product",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProductConfigSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("order", models.IntegerField(default=0)),
                ("step_number", models.IntegerField(default=1)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config_sections",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "db_table": "product_config_section",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ProductConfigOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option_id", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "price_usd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("badge", models.CharField(blank=True, max_length=50)),
                ("is_default", models.BooleanField(default=False)),
                ("overlay_icon", models.CharField(blank=True, max_length=50)),
                ("overlay_label", models.CharField(blank=True, max_length=100)),
                ("overlay_position", models.CharField(blank=True, max_length=100)),
                ("overlay_color", models.CharField(blank=True, max_length=200)),
                ("order", models.IntegerField(default=0)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="products.productconfigsection",
                    ),
                ),
            ],
            options={
                "db_table": "product_config_option",
                "ordering": ["order"],
            },
        ),
    ]
